name: "generate-breakout-game-from-github-contribution-graph"
description: "Generate a Breakout game svg from github contribution graph"
author: "cyprieng"

branding:
  icon: "image"
  color: "green"

inputs:
  github_username:
    description: "Github username"
    required: true
  github_token:
    description: "Github token used to fetch the contributions. Default to the action token if empty."
    required: false
    default: ${{ github.token }}
  enable_empty_days:
    description: "Empty days be used as bricks"
    required: false

runs:
  using: node20
  main: dist/cli.js
