name: "generate-breakout-game-from-github-contribution-graph"
description: "Generate a Breakout game svg from github contribution graph"
author: "cyprieng"

branding:
  icon: "image"
  color: "green"

inputs:
  github_username:
    description: "Github username"
    required: true
  github_token:
    description: "Github token used to fetch the contributions. Default to the action token if empty."
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 23
    - run: npm install
      shell: bash
    - run: mkdir -p output
      shell: bash
    - run: npx ts-node src/cli.ts "${{ inputs.github_username }}" "${{ inputs.github_token }}" light > output/light.svg
      shell: bash
    - run: npx ts-node src/cli.ts "${{ inputs.github_username }}" "${{ inputs.github_token }}" dark > output/dark.svg
      shell: bash
